### PR TITLE
Adding verbs for GET and PUT

### PR DESCRIPTION
**Pull request by juanpaucar**
@dbp could you check it please?

I tried to add patch too but, currently it is not in Snap.Test, so probably is a good idea to have it there first.
I changed the Text adding the <html> tag since in a test you were trying `shouldNotHaveText` and looking for `<html>` and you didn't have it anyway on the text.

I also changed the handler for `"/params"` so we could correctly identify when a POST is called and when a PUT is called and if we eventually want to add PATCH it wouldn't be hard to test it.

So if you have some comment, please tell me

cc: @jsantos17 @sestrella

### CODE REVIEW

**Comment by dbp** [comment]
This looks pretty good. The only question I have is about the test for `PUT` for the `/test` endpoint. There isn't actually a handler for that (it only matches `GET`, `POST`, and `DELETE`). Since it's a negative test, I imagine it passes, but it passes because it failed to match any handler, rather than matching a handler but not having the content. I think if you add a handler for that (which can return an empty string, or really anything that isn't `<html>`), this'll be good to merge. 

Thanks!

**Comment by juanpaucar** [comment]
@dbp Thanks, i totally forgot to include that handler

**Comment by juanpaucar** [comment]
@dbp ping :)

**Comment by juanpaucar** [comment]
@dbp Hey, i just made the change, could you check it again, please?

**Comment by dbp** [comment]
@juanpaucar Thanks - sorry for the delay - it's now on hackage as 0.3.2.5.

**Pull request merged**
