### PR TITLE
1.0

### PR DESCRIPTION
**Pull request by imalsogreg**
These updates refer to snap HEAD and fix a faulty url in that submodule.
Also merging from hspec-snap master.

### CODE REVIEW

**Comment by dbp** [comment]
Hey Greg,

What do you need to do to get the test suite running from scratch (with stack)? Is it just a `git submodule update`? I'd like to get this branch passing the build - https://circleci.com/gh/dbp/hspec-snap/50

**Comment by imalsogreg** [comment]
Hey Daniel. I can attempt to get a stack setup here for experimenting tonight. snap 1.0 just [got released](https://www.reddit.com/r/haskell/comments/4wody6/announcing_snap_10/) (YAY!!) so that eliminates the need for submodules in hspec-snap, I'll just have to figure out how to bring in snap-core & snap-server from hackage in a stack.yaml.

**Comment by imalsogreg** [comment]
Quick update. This seems to be caused by an old version of `either` getting pulled in by heist's testsuite, which lost its `errors` dependency bounds when `errors` was removed from the library but accidentally left in the testsuite. I've pushed a patch to heist with no `errors` dependency at all and will ask the snap maintainers to push it to hackage soon.

Any chance you know how to force stack to use errors-2.1.2 (that's the version we would have picked if we'd kept the dep bounds on. In fact, we've updated the hackage metadata with that bound but it doesn't seem to have taken effect yet)? Or is it a bad idea to deviate by the version used in LTS?

**Comment by dbp** [comment]
Hey Greg - obviously it should get fixed upstream, but I'm totally happy to
have it overridden here - that decision doesn't affect downstream (just our
own build). If you set it as an extra dependency in the two stack.yaml
files (one for GJC 7.8, one for 7.10), that'll be the version it will use.
I'm on a phone so don't remember the exact syntax, but hopefully it's easy
to figure out!

**Comment by imalsogreg** [comment]
Ahh, great, that worked. Thanks a bunch! Maybe we can remove those from your stack.yaml when the heist issue is ironed out.

**Comment by dbp** [comment]
Great! Thanks for getting that all working!

**Comment by dbp** [comment]
@imalsogreg - Should we wait until the dependency issues are worked out to merge/release this? Or release it now, since those were only affecting the test suites?

**Comment by imalsogreg** [comment]
I can't think of a way that the testsuite issues would bother a downstream user. So I'd lean toward releasing now. What do you think?

**Comment by dbp** [comment]
Yeah, that sounds fine. I'll do that soon!

**Pull request merged**
