### PR TITLE
bumped text dep & formatted dep. list

### PR DESCRIPTION
**Pull request by dmjio**

### CODE REVIEW

**Comment by dbp** [comment]
Could you bump it on the test suite target too? Thanks!

**Comment by dmjio** [comment]
should be good now

**Comment by dbp** [comment]
Thanks!

**Comment by dbp** [comment]
And it's released now (as 0.3.2.2 - there was another minor version bump I accidentally hadn't pushed to github).

**Comment by dmjio** [comment]
fantastic, thank you

**Pull request merged**
