### PR TITLE
Support hspec 2.5

### PR DESCRIPTION
**Pull request by imalsogreg**
I've also bumped upper bounds on several other dependencies, and dropped bounds that were redundant between the test suite and main library.

### CODE REVIEW

**Comment by xplat** [comment]
Huh, I was working on this for a different project in the last couple of days.

**Comment by imalsogreg** [comment]
@dbp bump. Also, any interest in sharing maintainership of `hspec-snap`? I definitely plan to continue using it in `servant-snap` and would be happy to share the load.

**Comment by dbp** [comment]
Wow -- super odd. I got no email notification for this original pull request. I'm so sorry! 

To your second question -- yes, I'm absolutely interested in sharing mantainership. I haven't used snap in now... years, and have been happy to continue to merge / release things, but I would be _happier_ not to! I've just made you an admin on this repo. If you'd rather fork it into your own account, etc, I'm also fine with that...

**Comment by dbp** [comment]
@imalsogreg I'm going to merge this... though CI no longer works because the file hasn't been update from circle's v1.0 to v2.0 files. I've done this with plenty of projects and it isn't terribly hard, though if you aren't interested in doing it, I can probably take care of it.

**Comment by imalsogreg** [comment]
Awesome, thanks @dbp . Ahh, do I remember that you have a web framework of your in now? Thanks for admin bits on the repo! No need for me to fork. Could I get the same for hackage, too?

**Comment by dbp** [comment]
Sure -- just did!

**Comment by dbp** [comment]
Oh -- and yes -- hackage.haskell.org/package/fn -- it's essentially 50% of Snap (plus some routing tricks) bolted on top of WAI/Warp, so benefiting from that whole ecosystem of middleware, etc...

**Pull request merged**
