### PR TITLE
Add PUT to get TestResponse

### PR DESCRIPTION
**Pull request by juanpaucar**
@dbp Hey i was wondering if you think this is a good idea, i was needing to extend my test suit for some verbs and i think it would be simplier if verbs like put, delete, patch be added, please tell me if this works for you to add tests or other verbs

### CODE REVIEW

**Comment by dbp** [comment]
Hey, this looks great. If you want to add `delete` and `patch` in a similar way that's fine. And just add a few tests to cover the functionality, and this will be ready to merge. Hopefully the test suite (in the `spec` directory) is easy enough to understand, but feel free to reach out if you need any help.

**Comment by juanpaucar** [comment]
A quick question should i keep it with Text as parameters or ByteString for each function?

**Comment by dbp** [comment]
My preference is Text. I personally think it's a mistake that so many high-level APIs in Snap are `ByteString` rather than `Text` (my alternate Snap prelude, [dbp/snap-plus](https://github.com/dbp/snap-plus), overrides a bunch of things to be `Text`-native).

**Comment by juanpaucar** [comment]
@dbp i'm closing this PR to open a new one on this fork https://github.com/stackbuilders/hspec-snap thanks for your time

**Comment by dbp** [comment]
Sounds good.

**Pull request closed without merging**
