### PR TITLE
Add compatibility with StackageLTS 2.4

### PR DESCRIPTION
**Pull request by juanpaucar**
@dbp could you check it please, i just bumped some constraints so it could be compatible with [StackageLTS 2.4](http://www.stackage.org/lts/2.4)

\cc: @jsantos17 @sestrella

### CODE REVIEW

**Comment by dbp** [comment]
Is there a reason to not bump snap upper bound to 0.15? They are very good
about not releasing breaking changes on minor releases, so of 0.14.0.1
works I would guess any 0.14 works...

**Comment by juanpaucar** [comment]
@dbp you are right, i already bumped to <0.15 for snap, thanks

**Comment by dbp** [comment]
@juanpaucar Sorry for the delay - this is now on hackage as 0.3.2.6

**Comment by juanpaucar** [comment]
awesome, thanks

**Pull request merged**
