### PR TITLE
Add support for GHC 7.10

### PR DESCRIPTION
**Pull request by juanpaucar**
@dbp could you take a look please?

### CODE REVIEW

**Comment by juanpaucar** [comment]
This is what i got if i tried to compile without flexible context
```spec/Main.hs:200:11:
    Non type-variable argument
      in the constraint: Control.Monad.State.Class.MonadState App m
    (Use FlexibleContexts to permit this)
    When checking that ‘isE’ has the inferred type
      isE :: forall (m :: * -> *).
             (Control.Monad.IO.Class.MonadIO m,
              Control.Monad.State.Class.MonadState App m) =>
             m Bool
    In the second argument of ‘($)’, namely
      ‘do { let isE = use mv >>= ...;
            after (\ _ -> void $ tryTakeMVar mvar)
            $ it "should reflect stateful in handler"
              $ do { eval isE >>= shouldEqual True;
                     post "/setmv" M.empty;
                     .... };
            it "cleans up" $ eval isE >>= shouldEqual True }’
    In a stmt of a 'do' block:
      describe "stateful changes"
      $ do { let isE = use mv >>= ...;
             after (\ _ -> void $ tryTakeMVar mvar)
             $ it "should reflect stateful in handler"
               $ do { eval isE >>= shouldEqual True;
                      post "/setmv" M.empty;
                      .... };
             it "cleans up" $ eval isE >>= shouldEqual True }
```

**Comment by dbp** [comment]
This looks good - one question though - is something broken or incompatible with `aeson 0.8.1`?

**Comment by juanpaucar** [comment]
Attoparsec version that snap uses

**Comment by dbp** [comment]
@juanpaucar This is now released - Thanks! http://hackage.haskell.org/package/hspec-snap-0.3.2.7

**Comment by juanpaucar** [comment]
@dbp thank you

**Pull request merged**
